### ISSUE TITLE
RedBits Change Domain

### ISSUE THREAD

**Issue by imtroymaycloy** [Prowlarr/Prowlarr#1228]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

hello all,

According to their homepage, redbits change their domain extension from https://red-bits.com to https://redbits.xyz/
From now, the default redbits prowlarr configuration is https://red-bits.com

### Expected Behavior

fix domain to https://redbits.xyz/

### Environment

```markdown
- OS: 
- Prowlarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

[v0.4.9.2083] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status Moved code from API request
   at NzbDrone.Core.Indexers.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Definitions\Cardigann\CardigannParser.cs:line 51
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 314
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 509
RequestUri: https://red-bits.com/api/torrents/filter?api_token=(removed)&name=&sortField=created_at&sortDirection=desc&perPage=100&page=1;StatusCode: Moved;ContentType: text/html;ContentLength: 166;ContentSample: <html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>

[AB#4372](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4372)

**Comment by Qstick** [comment]
This was already fixed in https://github.com/Prowlarr/Indexers/commit/7e494dab151a2544d89961b03b8776e5070986e9

**Comment by bakerboy448** [comment]
run the definition refresh task

**Comment by carlogarro** [comment]
> 

Even if i update the indexer definiton in tasks tab, i still don't see the new one. I also just updated prowlarr to last version. Is something missing there? Thanks.

**Comment by carlogarro** [comment]
> run the definition refresh task
Even if i update the indexer definiton in tasks tab, i still don't see the new one. I also just updated prowlarr to last version. Is something missing there? Thanks.

**Comment by carlogarro** [comment]
> run the definition refresh task

Even if i update the indexer definiton in tasks tab, i still don't see the new one. I also just updated prowlarr to last version. Is something missing there? Thanks.

**Comment by bakerboy448** [comment]
Trace logs of the refresh task?
And if you view the definition file what's it look like?

**Comment by carlogarro** [comment]
> Trace logs of the refresh task? And if you view the definition file what's it look like?

When doing the refresh task nothing is saved in the logs. But it is marked as completed.
The definition file looks as the old one. It's still the old url.

**Comment by bakerboy448** [comment]
That's not possible.  Trace logs will show details of it running. Perhaps you're looking at the info logs which are informational only and not useful for any debugging?

**Comment by carlogarro** [comment]
> That's not possible. Trace logs will show details of it running. Perhaps you're looking at the info logs which are informational only and not useful for any debugging?

You are right. I did it now and i got this. It seems it updated correctly but the definition file didn't change.

`2022-12-10 17:27:48.4|Debug|HttpClient|Downloading [https://indexers.prowlarr.com/master/7/package.zip] to [/config/Definitions/indexers.zip]
2022-12-10 17:27:48.5|Debug|HttpClient|Downloading Completed. took 0s
2022-12-10 17:27:48.6|Debug|IndexerDefinitionUpdateService|Updated indexer definitions`

**Comment by Qstick** [comment]
Should be fixed now. Try another update.

**Comment by carlogarro** [comment]
> Should be fixed now. Try another update.

No... it still appears the older one.

**Comment by Qstick** [comment]
![Screenshot_20221210-141637](https://user-images.githubusercontent.com/376117/206873749-aed37c0b-e120-4628-a473-8a8976699dc0.png)

You refresh again?
